### ISSUE TITLE
Redesign of the `Configuration` screen

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#115]
![image](https://user-images.githubusercontent.com/1894/151109416-e52474b8-4c29-44df-898a-914e19d80189.png)

Ref: https://github.com/code-ready/crc-react-components/issues/27

**Comment by gbraad** [comment]
The tabs would be :
  * `Basic`
  * `Proxy`
  * `Other`
  * `...`
 
with the content based on a container
The elements in the example are captured in a `FormGroup` to label them.
The `Save` and `Reset` are in an `ActionGroup` and defined outside the container.

The container should have a defined `height` as otherwise the `ActionGroup` elements would move around.

**Comment by adrianriobo** [comment]
Which could be the best option for adding the pull secret change option:

1. Next to the preset selection

2. On a Openshift specific configuration tab (dynamically shown based on preset selection)

The idea would be have minimum parameters at basic tab. For Openshift preset the pull secret is required. At the moment the only step where this is validated is on start. 

There are certain constraints for doing it during onboarding process (https://github.com/code-ready/tray-electron/issues/106), those contratints I think do not apply here, so this can be validated at configuration time. Otherwise we can end on a situation where:

1. User onboard for podman
2. User change preset to podman (as no validation is thrown and he may not aware of pull secret) he just try to start
3. User start cluster 
4. User get notification of failure for start 
5. User gets window for pull secret (he still misses where this is at configuration window)
6. User start cluster (still need to check if resume the process as previously https://github.com/code-ready/tray-electron/issues/98)
7. Cluster is running    

New crc version is released, so user do `cleanup`. 

User may repeat steps again? 

If we add validation for the pull secret on configuration window we can avoid all those extra steps.

If pull secret is next to preset selection (as hidden and shown on openshift selection) it is obvious to the user where to add that information, if it is located at other tab still needs to find it.

**Comment by gbraad** [comment]
At the moment I can except the popup that is shown on start of the cluster that a pull secret is needed.
It might be an improvement to highlight the tab that information is missing.

I'll mock something up these days. First goal is to avoid a scrollbar #113

**Comment by gbraad** [comment]
![image](https://user-images.githubusercontent.com/1894/151382204-60474cca-8bdb-4a07-9090-6c7e6778b2b3.png)

**Comment by gbraad** [comment]
Looking into using labelinfo to fill the space:
![image](https://user-images.githubusercontent.com/1894/151494171-1b9268ea-0d61-46fe-a048-b5ccc8c94a5f.png)
