### ISSUE TITLE
Redesign of the `MiniStatus` window

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#126]
A possible design could be
![image](https://user-images.githubusercontent.com/1894/151908871-0ded5d81-fa9d-49c0-92e3-db2aabbcc5fd.png)

**where the Pause/Play button toggles between the states that the instance is in.**

Related to: https://github.com/code-ready/crc-react-components/issues/29

* button represents state of the instance
* delete actions is represented by a trash icon
* delete triggers confirmation dialog #130

**Comment by deboer-tim** [comment]
Having play & pause on the same button is confusing to me, e.g. which is it going to do? One option to fix this would be to alternate the icon based on the state, but then it has to be really clear what the current state is. It's clear when YouTube is playing because there is movement and sound and it immediately toggles between states, but with a VM the fan noise is a bit delayed and there are delays and unknown states. :) IMHO we're going to need a clear and separate current state (e.g. "Starting" label) beside the action.

IMHO Delete is also potentially confusing for new users, especially if you hadn't made the connection to a VM yet. You don't know if this is deleting the install, whether it is recoverable, how would I create a new one, etc. In this case I think there just needs to be a really clear confirmation dialog.

**Comment by gbraad** [comment]
> Having play & pause on the same button is confusing to me

where the Pause/Play button toggles between the states that the instance is in (this means the icon changes according to the state of the VM).


![image](https://user-images.githubusercontent.com/1894/152779625-8673bf26-19ca-4b30-8865-d3c13bebc68b.png)


----

 * The instance state is `stopped` or `unknown`:
![image](https://user-images.githubusercontent.com/1894/152800409-ff326401-72bd-40ca-baee-97182bcd0739.png)

 * the instance state is `starting`:
![image](https://user-images.githubusercontent.com/1894/152801496-1d092ab7-4b43-4e24-8414-49a3dcf3c176.png)

 * the instances state is `running`:
![image](https://user-images.githubusercontent.com/1894/152800449-6dc2ad90-158c-44ea-a8d5-dc245f9e51a0.png)

**Comment by gbraad** [comment]
>  I think there just needs to be a really clear confirmation dialog.

  * #130

I also suggest you to look at the doc that is shared between me, Kevin, and Beau of UX, as this have been addressed and discussed there.

**Comment by gbraad** [comment]
Would like to display memory, cpu and disk usage in 'real-time'.

For which
```javascript
import {
    OutlinedHddIcon,
    MemoryIcon,
    MicrochipIcon
} from '@patternfly/react-icons';
```
can be used. Originally discussed as part of https://github.com/code-ready/crc-react-components/issues/5

**Comment by gbraad** [comment]
* when stopped/stopping
![image](https://user-images.githubusercontent.com/1894/153133445-e37540b8-bbbb-4811-89dc-a043e0c12ebb.png)

* when starting
![image](https://user-images.githubusercontent.com/1894/153133742-1a9d0f87-161f-4d44-ad53-d82e491b4084.png)

* when running
![image](https://user-images.githubusercontent.com/1894/153133642-766f6cf4-557f-46bc-bf21-38fd767a3fe1.png)
