### ISSUE TITLE
[Spike] Investigate what is needed to make the tray work properly on Linux

### ISSUE THREAD

**Issue by gbraad** [crc-org/tray-electron#144]

**Comment by evidolob** [comment]
I made some tests on linux, on two DE. The common problem is that ministatus window is placed incorrectly.

On KDE(Plasma Workspace) tray app works out of box(plasma has system tray):
![Screenshot_20220216_103443](https://user-images.githubusercontent.com/929743/154226977-c705f238-bbf1-4504-bb59-828d84e85bf6.png)
![Screenshot_20220216_103505](https://user-images.githubusercontent.com/929743/154226994-5d3acc05-4e52-4fb9-b384-31bd44e7256e.png)

On gnome there are no system tray by default, tray app is running but there are no way to interact with it. System tray may be enabled with  https://extensions.gnome.org/extension/2890/tray-icons-reloaded/# We may advise users to install it. 

![Screenshot from 2022-02-16 10-30-08](https://user-images.githubusercontent.com/929743/154227347-885e8c19-90af-40aa-9e35-e48295cd788b.png)


![Screenshot from 2022-02-16 10-30-33](https://user-images.githubusercontent.com/929743/154227394-5beea723-0fb9-47e9-beec-d30e71f81a50.png)

Also on linux tray show menu only when `tray` object has menu object attached, otherwise right click event is ignored, so we cannot set menu dynamically, like we do for mac and windows.

**Comment by gbraad** [comment]
It is weird that that location is also misplaced. Is that because of bounds not being reported correctly?

**Comment by evidolob** [comment]
I don't know, need to check...

**Comment by evidolob** [comment]
I think ministatus positioning is not implemented correctly - https://github.com/code-ready/tray-electron/blob/master/main.js#L349-L354 
It always positioned on y `20` pixels

**Comment by gbraad** [comment]
Ideally this should be placed above the statusbar when clicked on the bottom, and slightly under when clicked at a top bar. It kinda depends on what we wanna do.

I also see that on macOS you can move the window around, while this is not possible on Windows. (seems to be the same for Linux).

**Comment by evidolob** [comment]
Yes, that true, I cannot move ministatus window on linux

**Comment by gbraad** [comment]
On certain platforms, especially the older macs, they would show a pseudo application icon on the desktop, when clicked it would resume the window instead of open ending a new application instance (unhide). Would this be possible?

**Comment by gbraad** [comment]
This is not something we will work on anymore.
