### ISSUE TITLE
No notification on setup errors during onboarding process

### ISSUE THREAD

**Issue by adrianriobo** [crc-org/tray-electron#209]
During the onboarding the setup process may end up failing on that condition from the onboarding perspective we do not get any notification. 

Actually the onboarding process seems to finish successfully so crc start should be possible directly

**Comment by praveenkumar** [comment]
This issue should be treated as high priority during current sprint. As a developer when I test and see setup succeed on UX I don't really care if it is working or not because of this false success. Either we catch error and show to the user or there should be some details view about `crc setup` run in UX.
